title: codbex
url: http://codbex.com

defaults:
  -
    scope:
      path: apps
      type: blogs
    values:
      layout: product
      category: apps
  -
    scope:
      path: components
      type: blogs
    values:
      layout: component
      category: components
  -
    scope:
      path: blogs
      type: blogs
    values:
      layout: blog
      category: blogs
  -
    scope:
      path: news
      type: blogs
    values:
      layout: news
      category: news
 